# Generated by Django 2.1 on 2020-11-21 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import equipment.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Списанное оборудование')),
                ('file', models.FileField(blank=True, upload_to='equipment_files/basket/%Y/%m/%d', validators=[equipment.validators.validate_file_extension])),
            ],
            options={
                'verbose_name_plural': 'Списание',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Basket_equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
            ],
            options={
                'verbose_name_plural': 'Списанное оборудование',
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Выдача оборудования')),
                ('customer', models.CharField(max_length=50, verbose_name='Клиент')),
                ('file', models.FileField(blank=True, upload_to='equipment_files/consumption/%Y/%m/%d', validators=[equipment.validators.validate_file_extension])),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расход',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Поступления оборудования')),
                ('supplier', models.CharField(max_length=50, verbose_name='Поставщик')),
                ('file', models.FileField(blank=True, upload_to='equipment_files/coming/%Y/%m/%d', validators=[equipment.validators.validate_file_extension])),
            ],
            options={
                'verbose_name': 'поступление',
                'verbose_name_plural': 'Поступления',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('in_stock', models.PositiveSmallIntegerField(verbose_name='В наличии')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Delivery', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Принятое оборудование',
                'verbose_name_plural': 'Принятое оборудование',
            },
        ),
        migrations.CreateModel(
            name='Issued_equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_count', models.PositiveSmallIntegerField(default=0, verbose_name='Возвращено')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Consumption', verbose_name='Клиент')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Выданное оборудование',
                'verbose_name_plural': 'Выданное оборудование',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_center', models.CharField(max_length=50, verbose_name='Сервисный центр')),
                ('date_from', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата передачи в ремонт')),
                ('date_back', models.DateField(blank=True, null=True, verbose_name='Дата возвращения из ремонта')),
                ('file_from', models.FileField(blank=True, upload_to='equipment_files/repair/from/%Y/%m/%d', validators=[equipment.validators.validate_file_extension])),
                ('file_back', models.FileField(blank=True, upload_to='equipment_files/repair/back/%Y/%m/%d', validators=[equipment.validators.validate_file_extension])),
            ],
            options={
                'verbose_name_plural': 'В ремонте',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Repair_equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
            ],
            options={
                'verbose_name_plural': 'Оборудование в ремонте',
            },
        ),
        migrations.CreateModel(
            name='Returned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Возврат оборудования')),
                ('supplier', models.CharField(max_length=50, verbose_name='Поставщик')),
                ('file', models.FileField(blank=True, upload_to='equipment_files/returns/%Y/%m/%d', validators=[equipment.validators.validate_file_extension])),
            ],
            options={
                'verbose_name': 'Возврат оборудования',
                'verbose_name_plural': 'Возврат оборудования',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Returned_equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair', models.BooleanField(verbose_name='В ремонт')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Returned', verbose_name='Поставщик')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Issued_equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Возвращенное оборудование',
                'verbose_name_plural': 'Возвращенное оборудование',
            },
        ),
        migrations.AddField(
            model_name='repair_equipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Returned_equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='repair_equipment',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Repair', verbose_name='Дата передачи в ремонт'),
        ),
        migrations.AddField(
            model_name='basket_equipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Returned_equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='basket_equipment',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Basket', verbose_name='Дата'),
        ),
    ]
